export type PastryProduct = {
  id: number;
  category: string;
  name: string;
  eyebrow: string;
  description: string;
  image: string;
  price: string;
  ingredients: string[];
  allergens: string[];
  notes: string[];
  conservation: string;
  weight: string;
  popular?: boolean;
};

export const pastryCatalog: PastryProduct[] = [
  { id: 1, category: "Gâteaux", name: "Gâteau aux fraises", eyebrow: "Création photographiée", description: "Une création décorée de fraises fraîches et de crème pochée. La composition exacte reste à confirmer avec Mélissa.", image: "/images/gateau-fraises.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Création artisanale", "Décor fleuri"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 2, category: "Entremets", name: "Chocolat & noisettes", eyebrow: "Création photographiée", description: "Un entremets au décor généreux de chocolat et de noisettes. Les ingrédients et la recette sont à valider avant commande.", image: "/images/entremets-chocolat-noisettes.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Chocolat", "Décor gourmand"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 3, category: "Number cakes", name: "Number cake thème marin", eyebrow: "Création sur mesure", description: "Un number cake décoré sur le thème marin, avec fruits et éléments décoratifs. Composition et format à confirmer.", image: "/images/number-cake-marin.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Décor sur mesure", "Thème marin"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 4, category: "Number cakes", name: "Number cake fruits rouges", eyebrow: "Création sur mesure", description: "Un number cake richement décoré de fruits rouges et de fleurs. Les détails de la recette sont à confirmer avec Mélissa.", image: "/images/number-cake-fruits-rouges.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Fruits rouges", "Décor fleuri"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 5, category: "Gâteaux", name: "Création framboise", eyebrow: "Création photographiée", description: "Un gâteau à la finition pochée, décoré de framboises et de fleurs. Recette et allergènes à confirmer.", image: "/images/gateau-framboises-fleurs.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Framboises", "Décor fleuri"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 6, category: "Number cakes", name: "Number cake chocolat", eyebrow: "Création sur mesure", description: "Un number cake au décor chocolaté, avec fleurs et détails gourmands. La composition exacte est à confirmer.", image: "/images/number-cake-chocolat.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Décor chocolaté", "Personnalisable"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 7, category: "Traiteur", name: "Planche gourmande", eyebrow: "Prestation traiteur sur demande", description: "Une grande planche festive composée et décorée pour un moment à partager. Contenu et quantités à définir selon votre demande.", image: "/images/traiteur-planche-festive.png", price: "Sur devis", ingredients: ["Composition à définir selon votre événement"], allergens: ["À confirmer avant commande"], notes: ["À partager", "Sur mesure"], conservation: "Modalités à préciser selon les produits retenus.", weight: "Quantités à définir selon le nombre de convives" },
  { id: 8, category: "Number cakes", name: "Number cake fleuri", eyebrow: "Création sur mesure", description: "Un number cake aux tons doux, décoré de fleurs. La recette et le format sont à confirmer.", image: "/images/number-cake-vanille-fleurs.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Décor floral", "Personnalisable"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 9, category: "Number cakes", name: "Number cake tropical", eyebrow: "Création sur mesure", description: "Un number cake au décor tropical et chocolaté, photographié par Mélissa.", image: "/images/number-cake-tropical.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Thème tropical", "Décor chocolaté"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 10, category: "Number cakes", name: "Number cake aux choux", eyebrow: "Création sur mesure", description: "Un number cake décoré de petits choux, de crème pochée et de fleurs.", image: "/images/number-cake-choux.png", price: "Tarif à confirmer", ingredients: ["Composition à confirmer avec Mélissa"], allergens: ["À confirmer avant commande"], notes: ["Petits choux", "Décor floral"], conservation: "Conseils à préciser selon la recette et la date de retrait.", weight: "Formats et nombre de parts à confirmer" },
  { id: 11, category: "Traiteur", name: "Verrines apéritives", eyebrow: "Prestation traiteur sur demande", description: "Des verrines salées décorées de radis et de jeunes pousses. Composition et quantités à préciser selon votre événement.", image: "/images/verrines-radis.png", price: "Sur devis", ingredients: ["Composition à définir selon votre événement"], allergens: ["À confirmer avant commande"], notes: ["Apéritif", "Sur mesure"], conservation: "Modalités à préciser selon les produits retenus.", weight: "Quantités à définir selon le nombre de convives" },
];
